### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Wurdy-gear** [Longoon12000/WordSearch#1]
I took your repository as the basis for my course project, I had some difficulties with reworking it, could you help? Not for free of course!

**Comment by Wurdy-gear** [comment]
Can I contact you for convenience? 
Facebook: https://www.facebook.com/profile.php?id=100036246586835
Skype: timati0008

**Comment by Wurdy-gear** [comment]
I am trying to make it so that the search takes place only in one file and not in the whole folder. I thought simply replacing FolderBrowserDialog with OpenFileDialog would solve the problem, but I get an error that I can't figure out.

**Comment by RainOrigami** [comment]
Hello!

Sorry I have been unavailable this past weekend.

For the change that you are describing changing the FolderBrowserDialog to an OpenFileDialog is a good first step.

Now I assume that you are working in the version 2.0.0.0 which resides inside the WPFWordSearch folder, meaning you have replaced the SearchPage.xaml.cs/folderBrowserDialog.

The folderBrowserDialog is used in SearchPage.xaml.cs/btnBrowse_Click to write the selected path to the txtPath.Text property, this (along with the initialisation of the folderBrowserDialog) needs to be replaced with the corresponding code to put the selected file path into the txtPath.Text property (the selected file is on the FileName property of the [OpenFileDialog](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.openfiledialog?view=netcore-3.1)). I also recommend that you add a file filter to the OpenFileDialog where you pre-filter on Word files (doc, docx, docm, ...).

In SearchPage.xaml.cs/btnSearch_Click the selected path is then passed to SearchPage.xaml.cs/search and along to the constructor in SearchProgress.xaml.cs which in turn is used in SearchProgress.xaml.cs/Window_Loaded to initiate the search for Word files in the path using the WordFileLocator.FindWordFiles method. This method returns a string array of paths of Word files.

Instead of using the WordFileLocator.FindWordFiles method you can instead put the path into a new string array and pass it directly to the GetSearchResults function in SearchProgress/Window_Loaded instead of using the result of WordFileLocator.FindWordFiles.

This would look like this:

`await Task.Run(() => this.SearchResults = this.search.GetSearchResults(new string[] {this.path}, this.expression, this.isRegex));`

I think this should be sufficient to change the search to use a single selected file instead of searching through a whole directory.

Let me know if this was useful or if you're stuck at some point.

**Comment by Wurdy-gear** [comment]
Wow, thanks for answering, I thought you'd ignore me. Yes, everything worked out, I didn't think of changing await Task.Run (() in SearchPage.xaml.cs, in the end everything works.

**Comment by RainOrigami** [comment]
Great! If you need any further help just reply to this issue! Good luck with your course!

**Comment by Wurdy-gear** [comment]
In general, I have little time, I need to remake the program, and if I understand myself, I will not meet the deadlines.
I want to ask you to remake the program, there are, in theory, small changes, I am ready to pay $ 15, I don’t know if this is a lot for the CIS countries, correct if not right.
In general, there is a Word document, it contains links directly in the text in this format: [1] and they must be mentioned in order in the text, [1] text-text-text [2] as an example, and I need to make the program so that it checks whether the numbering of links is in order, if there is an error somewhere, then you need to display where the error is.
Sorry if I'm too arrogant or something like that, if you're busy then tell me about it.

**Comment by RainOrigami** [comment]
From your description I would assume that the following text:

```
This is text with a[1] link. There is more text with links[2].
Some links[3] are here and others[4] are there.
There’s effin’ links[6] everywhere[5].
And if the order[7] is so wrong,
or if there’s dupes[7] that don’t belong,
we’ll find them.
And if links[9] are all[10] fucked up then there’s gonna be a lot of results[11].
```

would result in the listing of:

- links[6]
- everywhere[5]
- order[7]
- dupes[7]
- links[9]

Please check the branch [linkOrderSearch](https://github.com/Longoon12000/WordSearch/tree/linkOrderSearch) which is where I have implemented this behaviour:

![image](https://user-images.githubusercontent.com/51454971/89220031-35759180-d5d1-11ea-8eed-88af36aa29d3.png)

Test Word file: [test.docx](https://github.com/Longoon12000/WordSearch/files/5018076/test.docx)

**Edit**: oh and most of the logic is in Search.cs/findInDocument.

**Comment by Wurdy-gear** [comment]
I probably didn’t put it that way, now I’ll show you an example of the text, don’t look at the language, the point here is just to check if the numbers in brackets are in order.
`When developing any Android [1] application, the developer needs to store the data that his application operates on. You can store them both locally on the device and in the cloud storage. For example, in Firebase Cloud Storage. Some applications combine all these methods of storing data. Most modern Android applications are able to synchronize data, store settings and work without the Internet, using data previously recorded in the local storage [2].`
The numbers in brackets are simply a reference to some source of literature. Like this:
`BIBLIOGRAPHIC LIST
1. Deytel, P. Android for programmers: creating applications [Text] / P. Deytel - SPb .: Peter, 2012. - 576 p.
2. Kotlyarov, V.P. Basics of software testing [Text] / V.P. Kotlyarov - SPb .: Binom, 2009 .-- 496 p.
3. Goloshchapov, A.L. GoogleAndroid. Creation of applications for smart phones and tablet PCs [Text] / А.L. Goloshchapov - SPb .: Peter, 2012 .-- 315 p.`
And I just need to check if the numbers in brackets are in order (links)

**Comment by RainOrigami** [comment]
Okay, I am not sure about the output so for convenience I've re-made the thing from scratch and split it up in a library that does the search and an example console application for how to use the search and check the order, so you can use the search in any way you like (eg. with UI or integrated into another project or as a web service etc.). It's not a lot of code and I've commented everything so it should be very easy to understand and modify.

What it does is, it checks if all the numbers inside brackets are in order, like this:

**WordLinkOrder/WordLinkOrder.cs** is the class for executing the search for all occurrences of [n] in a Word document. The constructor takes the path, the Run method executes the search and returns an int array of all references in order of appearance in the document.

**WordLinkOrderChecker/Program.cs** is an example on how to use the **WordLinkOrder** class and also performs a simple check, for each match it will check if the current match is the previous match + 1 (so if matches were [1] [2] [3]...), if not it would output the reference number and the expected reference number, then proceed with the current match as the previous match. The implication is that in the case of [1] [3] [2] [4] it will mark 3, 2 and 4 as bad references because after 1 it'd expect 2 but got 3, then for 2 it would expect 4 as the previous match was 3, and finally at 4 it would expect 3 as the previous match was 2.

I'm still not sure if this is the matching you'd expect but the code is very simple and you can easily adjust it to your needs:
- If you need to adjust the order detection, check **WordLinkOrderChecker/Program.cs** where the foreach contains all code that checks for the correct order.
- If you need to adjust the output of the order detection (eg. don't print which references were in bad order, just print either "There are references in the wrong order!" or "All references are in the correct order!", or print all references and mark bad ones in the output) you can edit the foreach inside **WordLinkOrderChecker/Program.cs**.
- If you need to adjust the matching, check **WordLinkOrder/WordLinkOrder.cs** which just takes a regular expression to search, there you can change the matching pattern.
- If you want to add a proper UI you can create a new WinForms/WPF/ASP/... project and add the **WordLinkOrder** project as reference, execute the **WordLinkOrder** as done in **WordLinkOrderChecker/Program.cs** and then handle the resulting int array as required in the UI.

Example:

![image](https://user-images.githubusercontent.com/51454971/89284671-6d231e80-d64f-11ea-9cf0-379e2b8273f8.png)

It's all checked in to the branch [linkOrderSearch](https://github.com/Longoon12000/WordSearch/tree/linkOrderSearch).

**Comment by Wurdy-gear** [comment]
Yes, everything works, I just fixed a small bug associated with the variable "lastNumber" the last number found in the text was taken there, because of this, for example, when finding [22] and after him [8] then it wrote that [23] was expected, although in fact it was expected in general [2], well, this is nothing I fixed, everything works,
```
// Check reference order
            int firstNumber = 0;
            int lastNumber = 0;
            bool hasBadReferences = false;
            foreach (int reference in references)
            {
                if (reference != firstNumber + 1)
                {

                    Console.WriteLine($"Bad reference order found: Got [{reference}] but expected [{lastNumber + 1}]!");
                    hasBadReferences = true;
                }

                firstNumber = reference;
                lastNumber=lastNumber+1;
            }
```
 it remains to attach the whole thing to the visual interface of your program, which I am doing now. 
Thank

**Comment by Wurdy-gear** [comment]
I had difficulties with the logic of work, I created the main form on which there is just a file selection button and a text line in which the path and the button to start the entire program are written.
![image](https://user-images.githubusercontent.com/68186484/89438901-73ea8800-d75a-11ea-9e18-3ddb6b25d874.png)
`void btnSearch_Click(object sender, RoutedEventArgs e)
        {
            string path = txtPath.Text;

            if (String.IsNullOrEmpty(path))
            {
                System.Windows.MessageBox.Show("No search path was provided. Please enter or select a path to search in.", "Missing search path", MessageBoxButton.OK, MessageBoxImage.Error);
                return;
            }
            registryKey.SetValue("Path", path);//Register rewriting

            //passing to path function

            WordLinkOrder.WordLinkOrder wordLinkOrder = null;
            try
            {
                wordLinkOrder = new WordLinkOrder.WordLinkOrder(path);
            }
            catch (FileNotFoundException ex)
            {
                Console.Error.WriteLine($"The file {ex.FileName} could not be found.");
                return;
            }
            //Running a check
            int[] references = wordLinkOrder.Run();

            // Check reference order
            int firstNumber = 0;
            int lastNumber = 0;
            bool hasBadReferences = false;
            foreach (int reference in references)
            {
                if (reference != firstNumber + 1)
                {
                    //There should be some other code here
                    //Console.WriteLine($"Bad reference order found: Got [{reference}] but expected [{lastNumber + 1}]!");
                    hasBadReferences = true;
                }

                firstNumber = reference;
                lastNumber = lastNumber + 1;
            }
        }`
I on btnSearch_Click set sending the file path to the WordLinkOrder function, and also launching wordLinkOrder.Run () and immediately checking links, I understand that this is not correct, but I don’t understand how to do it correctly.
My whole solution looks like this:
![image](https://user-images.githubusercontent.com/68186484/89439463-4baf5900-d75b-11ea-94a1-72c67212a42c.png)
Search and Program do nothing there, all the code is commented out and the ResulPage page is not implemented, it is empty.
As I understand it, I need to create a class in which there will be the entire miscalculation of the search for links, and in btnSearch_Click, you just need to run this class, but there is still ResultPage how to implement it is not clear at all.

**Comment by RainOrigami** [comment]
Very good!

You can take the result of wordLinkOrder.Run() (the int array) and pass it to ResultPage and do the calculation there, then display it. I forgot how the result page ist called, but I will provide an example when I get home in a few hours.

**Comment by Wurdy-gear** [comment]
Thank you, I will now try to upload the repository to my account and send it to you to make it easier for you to understand the situation!

**Comment by Wurdy-gear** [comment]
https://github.com/Wurdy-gear/Link-Checker 
So I downloaded the repository, only there the file "v16" I don't know where it came from, it's not needed.

**Comment by RainOrigami** [comment]
> only there the file "v16" I don't know where it came from, it's not needed

Those are files created by Visual Studio that are not required in the repository. For new repositories you should always add a ".gitignore" file that excludes unwanted files, for Visual Studio this is a template: https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

Now the ResultsPage is a Page, which usually uses a NavigationWindow for displaying (in the original code it was `MainWindow : NavigationWindow` which loaded Pages, like the search page or results page). Your MainWindow however is a Window, so I'm not sure if it's possible to open a page on it. You may have to re-create ResultsPage as a Window too so you can call it using `new ResultsPage(references).Show()` or something like that.
Also the MainWindow needs to be closed/hidden so I think the code would look like this:

```
int[] references = wordLinkOrder.Run();
this.Hide(); // Hide current MainWindow
new ResultsWindow(references).ShowDialog(); // Show ResultsWindow modally
this.Close(); // Once ResultsWindow is closed also close this window to exit the app
// alternatively (comment this.Close() and uncomment the next line for this to work):
// this.Show(); // Once ResultsWindow is closed, show the MainWindow again to process another file
```

Anyway, you can pass the int array to the constructor of ResultsPage (`new ResultsPage(references)`) and then do the order check that is in MainWindow.xaml.cs line 78-93 in the constructor too. Then display it any way you like on there.

**Comment by Wurdy-gear** [comment]
I updated the repository, everything works, it remains to draw a beautiful output, do not tell me where and how to call ResultWinds and what to write in it so that how is the output in your program?

**Comment by Wurdy-gear** [comment]
Probably I asked a question that was too incomprehensible, so I will try to specify.
I have an array int [] after working WordLinkOrder, after that i try to process this array in class Check
 ```
            //Running a check
            int[] references = wordLinkOrder.Run();
            //System.Windows.Forms.MessageBox.Show("Check запущен и начал проверку");
            // Check reference order
            int firstNumber = 0;
            int lastNumber = 0;
                foreach (int reference in references)
                {
                    if (reference != firstNumber + 1)
                    {
                    //System.Windows.Forms.MessageBox.Show($"Bad reference order found: Got [{reference}] but expected [{lastNumber + 1}]!");
                    //Console.WriteLine($"Bad reference order found: Got [{reference}] but expected [{lastNumber + 1}]!");
                    }
                    firstNumber = reference;
                    lastNumber = lastNumber + 1;
                }
            //There should be a call to a new window with the results
            new ResultWindow(references).ShowDialog(); // Show ResultsWindow modally
```
And I have the following code in ResultWindow.xaml
```
<Window x:Class="Practic.ResultWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Practic"
        mc:Ignorable="d"
        Title="ResultsWindow" Height="450" Width="800">
    <TextBlock Text="{Binding references[]}" TextWrapping="Wrap" Margin="43,32,0,0" />
</Window>
```
And in ResultWindow.xaml.cs
```
    public partial class ResultWindow : Window
    {

        public ResultWindow(int [] references)
        {
            InitializeComponent();
        }
    }
```
But this all does not work, nothing is displayed at all, I am an absolute 0 in visual programming, you can tell me how to make it display an array, and it is necessary that it displays and shows exactly where it was found, just like in your program.

**Comment by RainOrigami** [comment]
> it displays and shows exactly where it was found

What exactly do you mean by "show exactly where it was found"?

The very first version already had this implemented, see the screenshot from [this comment](https://github.com/Longoon12000/WordSearch/issues/1#issuecomment-668204439):
![image](https://user-images.githubusercontent.com/51454971/90020117-b27ac800-dcaf-11ea-8c66-1b1e2d3fd9f6.png)

The int array only contains the numbers of the references, no additional information. If you want more information, like the surrounding text, then this needs to be tracked too so you can't use an int array but have to use a SearchResult class where all the required data is stored, like in the [initial commit](https://github.com/Longoon12000/WordSearch/tree/80473329f43ab86eb4fb3170c831e50e921ba709).

Anyway I recommend that you check out the initial ResultPage on how you can display an array of data (I'm using data bindings, which is fairly easy).

**Comment by Wurdy-gear** [comment]
> > it displays and shows exactly where it was found
> 
> What exactly do you mean by "show exactly where it was found"?
> 
> The very first version already had this implemented, see the screenshot from [this comment](https://github.com/Longoon12000/WordSearch/issues/1#issuecomment-668204439):
> ![image](https://user-images.githubusercontent.com/51454971/90020117-b27ac800-dcaf-11ea-8c66-1b1e2d3fd9f6.png)
> 
> The int array only contains the numbers of the references, no additional information. If you want more information, like the surrounding text, then this needs to be tracked too so you can't use an int array but have to use a SearchResult class where all the required data is stored, like in the [initial commit](https://github.com/Longoon12000/WordSearch/tree/80473329f43ab86eb4fb3170c831e50e921ba709).
> 
> Anyway I recommend that you check out the initial ResultPage on how you can display an array of data (I'm using data bindings, which is fairly easy).

But the repository that you mentioned is the same console project, although in the screenshot, it is not a console project, I don't understand what?
![image](https://user-images.githubusercontent.com/68186484/90044425-ac501000-dcde-11ea-9cac-d6f6dc8229a5.png)
This is implemented in the repository, you did not throw off the code on how to do this:
![image](https://user-images.githubusercontent.com/68186484/90044504-c7228480-dcde-11ea-9360-b66af6681e6b.png)

**Comment by RainOrigami** [comment]
> But the repository that you mentioned is the same console project, although in the screenshot, it is not a console project, I don't understand what?

Yes, it's the commit [80473329f43ab86eb4fb3170c831e50e921ba709](https://github.com/Longoon12000/WordSearch/tree/80473329f43ab86eb4fb3170c831e50e921ba709).

**Comment by Wurdy-gear** [comment]
There are problems with displaying the displayed text.
![image](https://user-images.githubusercontent.com/68186484/90121511-1ca57280-dd6d-11ea-8335-3e81078b4250.png) the Text that is displayed before and after the found link is programmed here right?
```
searchResults.Add(new SearchResult()
                        {
                            FilePath = filePath,
                            Match = currentMatch,
                            BeforeMatch = documentText.Substring(Math.Max(match.Index - this.resultRadius, 0), this.resultRadius),
                            AfterMatch = documentText.Substring(match.Index + match.Value.Length, documentText.Length - Math.Min(match.Index + match.Value.Length + this.resultRadius, documentText.Length))
                        });
```
Can it be configured to render from paragraph to paragraph without the complexity of your original project, i.e. without positionWordStart, positionWordEnd, splitDocument?
More specifically, how can you find the beginning of a paragraph and its end?

**Comment by Wurdy-gear** [comment]
And another huge request, can you explain in more detail how this function works? 
```
private string readDocument(string filePath)
        {
            if (Token.IsCancellationRequested)
                return String.Empty;

            this.updateProcess($"Reading file {this.Current + 1}/{this.Total} ({Path.GetFileNameWithoutExtension(filePath)})", this.Current, this.Total);

            Word.Document document = this.application.Documents.Open(FileName: filePath, ReadOnly: true, Visible: false);

            try
            {
                string documentText = String.Join(paragraphSeparator, document.StoryRanges.OfType<Word.Range>().SelectMany(r => r.Paragraphs.OfType<Word.Paragraph>()).Select(p => p.Range.Text)).Replace("\v", paragraphSeparator);

                document.Close(SaveChanges: false);

                this.updateProcess($"Read file {this.Current + 1}/{this.Total} ({Path.GetFileNameWithoutExtension(filePath)})", this.Current, this.Total);

                return documentText;
            }
            catch (Exception)
            {
                return "";
            }
        }
```
Namely this line
```
    string documentText = String.Join(paragraphSeparator, document.StoryRanges.OfType<Word.Range>().SelectMany(r => r.Paragraphs.OfType<Word.Paragraph>()).Select(p => p.Range.Text)).Replace("\v", paragraphSeparator);
```

**Comment by Wurdy-gear** [comment]
I want to know how the text that is displayed is created, in as much detail as possible, please.

**Comment by Wurdy-gear** [comment]
I need to somehow find a paragraph, as you do when you put a tick in the checkbox paragraph.
![image](https://user-images.githubusercontent.com/68186484/90181409-7172d880-ddc1-11ea-8f51-1bcaacc13343.png)
How do I find the beginning of a paragraph?
My display is adjusted manually and I want to make it seem like I always have a checkmarked paragraph in the checkbox:
![image](https://user-images.githubusercontent.com/68186484/90181466-8cdde380-ddc1-11ea-8615-1bc63100d1a5.png)

**Comment by RainOrigami** [comment]
To find the beginning of a paragraph I suggest that you find the previous `\n` from the location of the match. Same for the end of the paragraph where you'd find the next `\n`.

**Comment by Wurdy-gear** [comment]
And how exactly to search with which function?

**Comment by RainOrigami** [comment]
Check this code: https://github.com/Longoon12000/WordSearch/blob/80473329f43ab86eb4fb3170c831e50e921ba709/WPFWordSearch/Search/Search.cs#L71-L77

There is a BeforeMatch and AfterMatch in SearchResult which is filled here with the "radius" text. Instead of using radius you have to find newlines.

Example:

documentText.Substring(0, match.Index) gives you all text from beginning to the match, so you can use LastIndexOf to find the position of the newline before the match.Index.
Then you can use IndexOf(..., match.Index) to find the position of the newline after the match.
You can then use Substring on documentText to get the text you want and put it in Before/AfterMatch or replace Before/AfterMatch with a variable where you put in the whole paragraph.

**Comment by Wurdy-gear** [comment]
Thank you very much, I did everything, how can I thank you?

**Comment by RainOrigami** [comment]
No need!

If everything is done you can close this issue.

**Comment by Wurdy-gear** [comment]
Thanks a lot again!
